<?php
return [
	
    'WebMessageCode' => [
    	'100' => 'Teacher added successfully',
    	'101' => 'Teacher updated successfully',
    	'102' => 'Teacher deleted successfully',
    	'103' => 'Only %s file(s) can be imported',
    	'104' => 'File is blank!',
    	'105' => 'Header missing  %s',
        '106' => 'Data Missing for line %s',
    	'107' => 'Password changed successfully.',
    	'108' => 'Password not updated.',
    	'109' => 'Current Password does not match.',
        '111' => 'Help ticket generated successfully.',
        '112' => 'Updated Successfully.',
        '113' => 'Notification id missing.',
        '114' => 'Student number empty.',
        '115' => 'Student Notified Successfully.',
        '116' => 'Message Send Successfully.',
        '117' => 'Error Code %s, Please contact Support',
        '118' => 'Error! You don\'t have permission, Please contact Support',
        '119' => 'Something went wrong, Please try again.',
		'120' => 'Class and Section not found',
        '121' => 'Something went wrong!',
        '122' => 'Timetable imported successfully!',
        '123' => 'Class %s successfully',
		'124' => 'Profile Updated Successfully.',
		'125' => 'Class Created Successfully.',
		'126' => 'Teacher not found.',
		'127' => 'Class Course Created Successfully.',
		'128' => 'Student details missing.',
		'129' => 'Student details wrongly updated.',
		'130' => 'Student added successfully',
		'131' => 'Topic Updated successfully',
		'132' => 'Email or Phone is required!!',
		'133' => 'Invalid Phone no!!',
		'134' => 'Help Ticket Status Updated.',
		'135' => 'Assignment Successfully Assign.',
		'136' => 'Issue while uploading students file, if issue persists, contact Admin/Support',
		'137' => 'CSV file Header/(1st line) mismatch!!, check the file format!!',
		'138' => 'Student number or Email empty.',
		'139' => 'Student deleted successfully',		
	],	
	'Email' => [
		'101' => '',
	]
];
